export const searchData = {
    "statusCode": 200,
    "message": "kits found successfully.",
    "result": {
        "content": [
            {
                "id": 1,
                "kitNo": 222222222222,
                "oem": "APPLE",
                "status": "Available",
                "fpsNumber": 7283728238,
                "salesUser": "",
                "dateOfPurchase": null,
                "installationDate": null,
                "zone": null,
                "territory": null,
                "district": null,
                "deviceModel": null,
                "imei1": null,
                "imei2": null,
                "mobileNo": 8107465880,
                "channelType": null,
                "channelName": null,
                "ownershipId": 1,
                "statusReason": null,
                "warrentyPeriod": null,
                "createdBy": null,
                "createdOn": null,
                "updatedBy": null,
                "updatedOn": null
            },
            {
                "id": 2,
                "kitNo": 34838747883,
                "oem": "apple",
                "status": "Available",
                "fpsNumber": 7283728238,
                "salesUser": "",
                "dateOfPurchase": null,
                "installationDate": null,
                "zone": null,
                "territory": null,
                "district": null,
                "deviceModel": null,
                "imei1": null,
                "imei2": null,
                "mobileNo": 8107465880,
                "channelType": null,
                "channelName": null,
                "ownershipId": 1,
                "statusReason": null,
                "warrentyPeriod": null,
                "createdBy": null,
                "createdOn": null,
                "updatedBy": null,
                "updatedOn": null
            },
            {
                "id": 3,
                "kitNo": 3943494309,
                "oem": "airtel",
                "status": "Available",
                "fpsNumber": 7283728238,
                "salesUser": "",
                "dateOfPurchase": "2019-07-22T07:06:40.000+0000",
                "installationDate": "2019-07-22T07:06:40.000+0000",
                "zone": "UG North",
                "territory": null,
                "district": null,
                "deviceModel": "apple",
                "imei1": null,
                "imei2": null,
                "mobileNo": 8107465880,
                "channelType": "sales p",
                "channelName": "sales portal",
                "ownershipId": 1,
                "statusReason": null,
                "warrentyPeriod": "2019-07-22T07:06:40.000+0000",
                "createdBy": "lovely",
                "createdOn": "2019-07-22T07:06:40.000+0000",
                "updatedBy": null,
                "updatedOn": null
            },
            {
                "id": 4,
                "kitNo": 222222222222,
                "oem": "APPLE",
                "status": "Available",
                "fpsNumber": 7283728238,
                "salesUser": "",
                "dateOfPurchase": null,
                "installationDate": null,
                "zone": null,
                "territory": null,
                "district": null,
                "deviceModel": null,
                "imei1": null,
                "imei2": null,
                "mobileNo": 8107465880,
                "channelType": null,
                "channelName": null,
                "ownershipId": 1,
                "statusReason": null,
                "warrentyPeriod": null,
                "createdBy": null,
                "createdOn": null,
                "updatedBy": null,
                "updatedOn": null
            },
            {
                "id": 5,
                "kitNo": 222222222222,
                "oem": "APPLE",
                "status": "Available",
                "fpsNumber": 7283728238,
                "salesUser": "",
                "dateOfPurchase": null,
                "installationDate": null,
                "zone": null,
                "territory": null,
                "district": null,
                "deviceModel": null,
                "imei1": null,
                "imei2": null,
                "mobileNo": 8107465880,
                "channelType": null,
                "channelName": null,
                "ownershipId": 1,
                "statusReason": null,
                "warrentyPeriod": null,
                "createdBy": null,
                "createdOn": null,
                "updatedBy": null,
                "updatedOn": null
            },
            {
                "id": 6,
                "kitNo": 21,
                "oem": "APPLE",
                "status": "Available",
                "fpsNumber": 7283728238,
                "salesUser": "",
                "dateOfPurchase": null,
                "installationDate": null,
                "zone": null,
                "territory": null,
                "district": null,
                "deviceModel": null,
                "imei1": null,
                "imei2": null,
                "mobileNo": 8107465880,
                "channelType": null,
                "channelName": null,
                "ownershipId": 1,
                "statusReason": null,
                "warrentyPeriod": null,
                "createdBy": null,
                "createdOn": null,
                "updatedBy": null,
                "updatedOn": null
            },
            {
                "id": 7,
                "kitNo": 22,
                "oem": "APPLE",
                "status": "Available",
                "fpsNumber": 7283728238,
                "salesUser": "",
                "dateOfPurchase": null,
                "installationDate": null,
                "zone": null,
                "territory": null,
                "district": null,
                "deviceModel": null,
                "imei1": null,
                "imei2": null,
                "mobileNo": 8107465880,
                "channelType": null,
                "channelName": null,
                "ownershipId": 1,
                "statusReason": null,
                "warrentyPeriod": null,
                "createdBy": null,
                "createdOn": null,
                "updatedBy": null,
                "updatedOn": null
            }
        ],
        "pageable": {
            "sort": {
                "sorted": true,
                "unsorted": false,
                "empty": false
            },
            "offset": 0,
            "pageNumber": 0,
            "pageSize": 20,
            "unpaged": false,
            "paged": true
        },
        "totalElements": 3,
        "totalPages": 1,
        "last": true,
        "size": 20,
        "number": 0,
        "numberOfElements": 3,
        "sort": {
            "sorted": true,
            "unsorted": false,
            "empty": false
        },
        "first": true,
        "empty": false
    }
}