// import { apiUrls } from './apiEndPoints';
// import { AppConstants } from './constant';
// import { PermissionIds } from '@src/core/utills/masterPermission';
// export const CardDataStore = {
//     cardInfo: [
//         {
//           image: "bulk-upload-kits.svg",
//           totalNum: "",
//           cardText: "cp_dashboard_card_bulk_upload_agent",
//           bulkStatus: true,
//           resource: "entity",
//           redirectUrl: "",
//           downloadImage: "download-template.svg",  
//           downloadTitle: "user_dashboard_card_download_template",
//           selectAgg: "",
//           endPoint: apiUrls.cpDownloadSampleFile,
//           sampleFileType: "text/csv", 
//           sampleTemplateName: AppConstants.sampleUserTemplate,
//           blacklisted: false,           
//           cpRole: "agents_cp_role",
//           uploadFileType: "zip",
//           uploadErrorMessage: "please_select_only_zip_file_type_error",
//           downloadFileName: "AgentTemplate",
//           moduleName: "CP",
//           permissionName: PermissionIds.AGENT_BULK_UPLOAD,
//           downloadSampleFilePermission: PermissionIds.DOWNLOAD_AGENT_BULK_UPLOAD_TEMPLATE,
//           downloadFailedFilePermission: PermissionIds.DOWNLOAD_FAILED_RECORDS_FILE_OF_AGENT,
//         },        
//         { 
//           image: "bulk-upload-kits.svg",
//           totalNum: "",
//           cardText: "cp_dashboard_card_bulk_upload_aggregators",
//           cardDownloadText: "cp_dashboard_card_bulk_upload_aggregator",
//           bulkStatus: true,
//           resource: "entity",
//           redirectUrl: "",
//           downloadImage: "download-template.svg",  
//           downloadTitle: "user_dashboard_card_download_template",
//           endPoint: apiUrls.cpDownloadSampleFile,
//           sampleFileType: "text/csv",
//           sampleTemplateName: AppConstants.sampleUserTemplate,
//           blacklisted: false,
//           moduleName: "CP",          
//           cpRole: "aggregators_cp_role",
//           uploadFileType: "zip",
//           uploadErrorMessage: "please_select_only_zip_file_type_error",
//           downloadFileName: "AggregatorsTemplate",
//           permissionName: PermissionIds.AGGRERATOR_BULK_UPLOAD,
//           downloadSampleFilePermission: PermissionIds.DOWNLOAD_AGGRERATOR_BULK_UPLOAD_TEMPLATE,
//           downloadFailedFilePermission: PermissionIds.DOWNLOAD_FAILED_RECORDS_FILE_OF_AGGREGATOR,
//         },
//         {
//           image: "bulk-upload-kits.svg",
//           totalNum: "",
//           cardText: "cp_dashboard_card_bulk_upload_blacklisted",
//           bulkStatus: true,
//           resource: "black_listing",
//           redirectUrl: "",
//           downloadImage: "download-template.svg",  
//           downloadTitle: "user_dashboard_card_download_template",
//           selectAgg: "cp_dashboard_card_bulk_upload_select_aggregator",
//           endPoint: apiUrls.cpDownloadSampleFile,
//           sampleFileType: "text/csv",
//           sampleTemplateName: AppConstants.sampleUserTemplate,
//           blacklisted: true,
//           moduleName: "CP",          
//           cpRole: "blacklisted_cp_role",
//           uploadFileType: "zip",
//           uploadErrorMessage: "please_select_only_zip_file_type_error",
//           downloadFileName: "BlacklistedTemplate",
//           permissionName: PermissionIds.BLACKLIST_ID_BULK_UPLOAD,
//           downloadSampleFilePermission: PermissionIds.DOWNLOAD_BLACKLIST_BULK_UPLOAD_TEMPLATE,
//           downloadFailedFilePermission: PermissionIds.DOWNLOAD_FAILED_RECORDS_FILE_OF_BLACKLIST,
//         },
//         /*
//         {
//           image: "bulk-upload-kits.svg",
//           totalNum: "",
//           cardText: "cp_dashboard_card_bulk_upload_freelancer_aggregators",
//           bulkStatus: true,
//           resource: "entity",
//           redirectUrl: "",
//           downloadImage: "download-template.svg",  
//           downloadTitle: "user_dashboard_card_download_template",
//           endPoint: apiUrls.cpDownloadSampleFile,
//           sampleFileType: "text/csv",
//           sampleTemplateName: AppConstants.sampleUserTemplate,
//           blacklisted: false,
//           moduleName: "CP",
//           permissionName: "",
//           cpRole: "freelance_aggregator_cp_role",
//           uploadFileType: "zip",
//           uploadErrorMessage: "please_select_only_zip_file_type_error",
//           downloadFileName: "FreelancerAggregatorsTemplate"
//         },
//         {
//           image: "bulk-upload-kits.svg",
//           totalNum: "",
//           cardText: "cp_dashboard_card_bulk_upload_edit_agent",
//           bulkStatus: true,
//           resource: "entity",
//           redirectUrl: "",
//           downloadImage: "download-template.svg",  
//           downloadTitle: "user_dashboard_card_download_template",
//           endPoint: apiUrls.cpDownloadSampleFile,
//           sampleFileType: "text/csv",
//           sampleTemplateName: AppConstants.sampleUserTemplate,
//           blacklisted: false,
//           moduleName: "CP",
//           permissionName: "",
//           cpRole: "edit_agent_cp_role",
//           uploadFileType: "zip",
//           uploadErrorMessage: "please_select_only_zip_file_type_error"
//         },
//         {
//           image: "bulk-upload-kits.svg",
//           totalNum: "",
//           cardText: "cp_dashboard_card_bulk_upload_edit_aggregators",
//           bulkStatus: true,
//           resource: "entity",
//           redirectUrl: "",
//           downloadImage: "download-template.svg",  
//           downloadTitle: "user_dashboard_card_download_template",
//           endPoint: apiUrls.cpDownloadSampleFile,
//           sampleFileType: "text/csv",
//           sampleTemplateName: AppConstants.sampleUserTemplate,
//           blacklisted: false,
//           moduleName: "CP",
//           permissionName: "",
//           cpRole: "edit_aggregators_cp_role",
//           uploadFileType: "zip",
//           uploadErrorMessage: "please_select_only_zip_file_type_error"
//         },
//         {
//           image: "bulk-upload-kits.svg",
//           totalNum: "",
//           cardText: "cp_dashboard_card_bulk_upload_edit_freelancer_aggregators",
//           bulkStatus: true,
//           resource: "entity",
//           redirectUrl: "",
//           downloadImage: "download-template.svg",  
//           downloadTitle: "user_dashboard_card_download_template",
//           endPoint: apiUrls.cpDownloadSampleFile,
//           sampleFileType: "text/csv",
//           sampleTemplateName: AppConstants.sampleUserTemplate,
//           blacklisted: false,
//           moduleName: "CP",
//           permissionName: "",
//           cpRole: "edit_freelance_aggregator_cp_role",
//           uploadFileType: "zip",
//           uploadErrorMessage: "please_select_only_zip_file_type_error"
//         }
//         */
//       ],
//       cardInfotxt:[
//         { 
//           image: "blacklisted.svg",
//           totalNum: "0",
//           cardText: "user_dashboard_card_black_listed",
//           showtxt: "blacklisted",
//           bulkStatus: false,
//           //redirectUrl: "/channel-partner/blacklisted", 
//           moduleName: "CP",
//           permissionName: PermissionIds.BLACKLISTED_CP_COUNT
//         },
//         {
//           image: "agents.svg",
//           totalNum: "0",
//           cardText: "user_dashboard_card_agents",
//           showtxt: "agent",
//           bulkStatus: false,
//           //redirectUrl: "/channel-partner/agents",
//           moduleName: "CP",
//           permissionName: PermissionIds.AGENT_COUNT
//         },
//         {
//           image: "freelance_agents.svg",
//           totalNum: "0",
//           cardText: "user_dashboard_card_free_agent",
//           showtxt: "freelance agent",
//           bulkStatus: false,
//           //redirectUrl: "/channel-partner/freelance-agents",
//           moduleName: "CP",
//           permissionName: PermissionIds.FREELANCE_AGENT_COUNT
//         },
//         {
//           image: "blacklisted.svg",
//           totalNum: "0",
//           cardText: "user_dashboard_card_aggregator",
//           showtxt: "aggregator",
//           bulkStatus: false,
//           //redirectUrl: "/channel-partner/aggregators",
//           moduleName: "CP",
//           permissionName: PermissionIds.AGGRERATOR_COUNT
//         },
//         /*
//         {
//           image: "freelance_agents.svg",
//           totalNum: "0",
//           cardText: "user_dashboard_card_free_aggr",
//           bulkStatus: false,
//           //redirectUrl: "/channel-partner/freelance-aggregators",
//           moduleName: "CP",
//           permissionName: 5
//         },        
//         {
//           image: "aggregator_maping.svg",
//           totalNum: "105",
//           cardText: "user_dashboard_card_agg_mapping",
//           showtxt: "aggregator_mapping",
//           bulkStatus: false,
//           //redirectUrl: "/channel-partner/aggregator-mappings",
//           moduleName: "CP",
//           permissionName: 6
//         },
//         {
//           image: "contracts.svg",
//           totalNum: "",
//           cardText: "user_dashboard_card_contract",
//           showtxt: "",
//           bulkStatus: false,
//           //redirectUrl: "/channel-partner",
//           moduleName: "CP",
//           permissionName: 7
//         },
//         {
//           image: "reports.svg",
//           totalNum: "",
//           cardText: "user_dashboard_card_report",
//           showtxt: "",
//           bulkStatus: false,
//           //redirectUrl: "/channel-partner",
//           moduleName: "CP",
//           permissionName: 8
//         }
//         */
//       ]
// }