export const kitRowData = [
  { "kit_no": 1001, "oem": "Lorem Ipsum", "device_model": "HDJK1231", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1002, "oem": "Lorem Ipsum", "device_model": "HDJK1232", "sales_user": "","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1003, "oem": "Lorem Ipsum", "device_model": "HDJK1233", "sales_user": "John Smith","channel_partner":"","kit_status":"Assigned" },
  { "kit_no": 1004, "oem": "Lorem Ipsum", "device_model": "HDJK1234", "sales_user": "John Smith","channel_partner":"","kit_status":"Assigned" },
  { "kit_no": 1005, "oem": "Lorem Ipsum", "device_model": "HDJK1235", "sales_user": "","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1006, "oem": "Lorem Ipsum", "device_model": "HDJK1236", "sales_user": "","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1007, "oem": "Lorem Ipsum", "device_model": "HDJK1237", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1008, "oem": "Lorem Ipsum", "device_model": "HDJK1238", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1009, "oem": "Lorem Ipsum", "device_model": "HDJK1239", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1010, "oem": "Lorem Ipsum", "device_model": "HDJK1230", "sales_user": "","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1011, "oem": "Lorem Ipsum", "device_model": "HDJK1231", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1012, "oem": "Lorem Ipsum", "device_model": "HDJK1232", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1013, "oem": "Lorem Ipsum", "device_model": "HDJK1233", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1014, "oem": "Lorem Ipsum", "device_model": "HDJK1234", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1015, "oem": "Lorem Ipsum", "device_model": "HDJK1235", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1016, "oem": "Lorem Ipsum", "device_model": "HDJK1236", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1017, "oem": "Lorem Ipsum", "device_model": "HDJK1237", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1018, "oem": "Lorem Ipsum", "device_model": "HDJK1238", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1019, "oem": "Lorem Ipsum", "device_model": "HDJK1239", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1020, "oem": "Lorem Ipsum", "device_model": "HDJK1230", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1021, "oem": "Lorem Ipsum", "device_model": "HDJK1231", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1022, "oem": "Lorem Ipsum", "device_model": "HDJK1232", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1023, "oem": "Lorem Ipsum", "device_model": "HDJK1233", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1024, "oem": "Lorem Ipsum", "device_model": "HDJK1234", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1025, "oem": "Lorem Ipsum", "device_model": "HDJK1235", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1026, "oem": "Lorem Ipsum", "device_model": "HDJK1236", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1027, "oem": "Lorem Ipsum", "device_model": "HDJK1237", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1028, "oem": "Lorem Ipsum", "device_model": "HDJK1238", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1029, "oem": "Lorem Ipsum", "device_model": "HDJK1239", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1030, "oem": "Lorem Ipsum", "device_model": "HDJK1230", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1031, "oem": "Lorem Ipsum", "device_model": "HDJK1231", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1032, "oem": "Lorem Ipsum", "device_model": "HDJK1232", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1033, "oem": "Lorem Ipsum", "device_model": "HDJK1233", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1034, "oem": "Lorem Ipsum", "device_model": "HDJK1234", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1035, "oem": "Lorem Ipsum", "device_model": "HDJK1235", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1036, "oem": "Lorem Ipsum", "device_model": "HDJK1236", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1037, "oem": "Lorem Ipsum", "device_model": "HDJK1237", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1038, "oem": "Lorem Ipsum", "device_model": "HDJK1238", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1039, "oem": "Lorem Ipsum", "device_model": "HDJK1239", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1040, "oem": "Lorem Ipsum", "device_model": "HDJK1230", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1041, "oem": "Lorem Ipsum", "device_model": "HDJK1231", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1042, "oem": "Lorem Ipsum", "device_model": "HDJK1232", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1043, "oem": "Lorem Ipsum", "device_model": "HDJK1233", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1044, "oem": "Lorem Ipsum", "device_model": "HDJK1234", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1045, "oem": "Lorem Ipsum", "device_model": "HDJK1235", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1046, "oem": "Lorem Ipsum", "device_model": "HDJK1236", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1047, "oem": "Lorem Ipsum", "device_model": "HDJK1237", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1048, "oem": "Lorem Ipsum", "device_model": "HDJK1238", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1049, "oem": "Lorem Ipsum", "device_model": "HDJK1239", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
  { "kit_no": 1050, "oem": "Lorem Ipsum", "device_model": "HDJK1230", "sales_user": "John Smith","channel_partner":"Lorem Ipsum","kit_status":"Assigned" },
];
