export const kitRowData = [

  { "kitNo": 1001, "oem": "Lorem Ipsum", "deviceModel": "HDJK1231", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1002, "oem": "Lorem Ipsum", "deviceModel": "HDJK1232", "salesUser": "", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1003, "oem": "Lorem Ipsum", "deviceModel": "HDJK1233", "salesUser": "John Smith", "channelName": "", "status": "Assigned" },
  { "kitNo": 1004, "oem": "Lorem Ipsum", "deviceModel": "HDJK1234", "salesUser": "John Smith", "channelName": "", "status": "Assigned" },
  { "kitNo": 1005, "oem": "Lorem Ipsum", "deviceModel": "HDJK1235", "salesUser": "", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1006, "oem": "Lorem Ipsum", "deviceModel": "HDJK1236", "salesUser": "", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1007, "oem": "Lorem Ipsum", "deviceModel": "HDJK1237", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1008, "oem": "Lorem Ipsum", "deviceModel": "HDJK1238", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1009, "oem": "Lorem Ipsum", "deviceModel": "HDJK1239", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1010, "oem": "Lorem Ipsum", "deviceModel": "HDJK1230", "salesUser": "", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1011, "oem": "Lorem Ipsum", "deviceModel": "HDJK1231", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1012, "oem": "Lorem Ipsum", "deviceModel": "HDJK1232", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1013, "oem": "Lorem Ipsum", "deviceModel": "HDJK1233", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1014, "oem": "Lorem Ipsum", "deviceModel": "HDJK1234", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1015, "oem": "Lorem Ipsum", "deviceModel": "HDJK1235", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1016, "oem": "Lorem Ipsum", "deviceModel": "HDJK1236", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1017, "oem": "Lorem Ipsum", "deviceModel": "HDJK1237", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1018, "oem": "Lorem Ipsum", "deviceModel": "HDJK1238", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1019, "oem": "Lorem Ipsum", "deviceModel": "HDJK1239", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1020, "oem": "Lorem Ipsum", "deviceModel": "HDJK1230", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1021, "oem": "Lorem Ipsum", "deviceModel": "HDJK1231", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1022, "oem": "Lorem Ipsum", "deviceModel": "HDJK1232", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1023, "oem": "Lorem Ipsum", "deviceModel": "HDJK1233", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1024, "oem": "Lorem Ipsum", "deviceModel": "HDJK1234", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1025, "oem": "Lorem Ipsum", "deviceModel": "HDJK1235", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1026, "oem": "Lorem Ipsum", "deviceModel": "HDJK1236", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1027, "oem": "Lorem Ipsum", "deviceModel": "HDJK1237", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1028, "oem": "Lorem Ipsum", "deviceModel": "HDJK1238", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1029, "oem": "Lorem Ipsum", "deviceModel": "HDJK1239", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1030, "oem": "Lorem Ipsum", "deviceModel": "HDJK1230", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1031, "oem": "Lorem Ipsum", "deviceModel": "HDJK1231", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1032, "oem": "Lorem Ipsum", "deviceModel": "HDJK1232", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1033, "oem": "Lorem Ipsum", "deviceModel": "HDJK1233", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1034, "oem": "Lorem Ipsum", "deviceModel": "HDJK1234", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1035, "oem": "Lorem Ipsum", "deviceModel": "HDJK1235", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1036, "oem": "Lorem Ipsum", "deviceModel": "HDJK1236", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1037, "oem": "Lorem Ipsum", "deviceModel": "HDJK1237", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1038, "oem": "Lorem Ipsum", "deviceModel": "HDJK1238", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1039, "oem": "Lorem Ipsum", "deviceModel": "HDJK1239", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1040, "oem": "Lorem Ipsum", "deviceModel": "HDJK1230", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1041, "oem": "Lorem Ipsum", "deviceModel": "HDJK1231", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1042, "oem": "Lorem Ipsum", "deviceModel": "HDJK1232", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1043, "oem": "Lorem Ipsum", "deviceModel": "HDJK1233", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1044, "oem": "Lorem Ipsum", "deviceModel": "HDJK1234", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1045, "oem": "Lorem Ipsum", "deviceModel": "HDJK1235", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1046, "oem": "Lorem Ipsum", "deviceModel": "HDJK1236", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1047, "oem": "Lorem Ipsum", "deviceModel": "HDJK1237", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1048, "oem": "Lorem Ipsum", "deviceModel": "HDJK1238", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1049, "oem": "Lorem Ipsum", "deviceModel": "HDJK1239", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
  { "kitNo": 1050, "oem": "Lorem Ipsum", "deviceModel": "HDJK1230", "salesUser": "John Smith", "channelName": "Lorem Ipsum", "status": "Assigned" },
];
